from os import environ, makedirs
from os.path import exists, join

import torch
from torch import is_tensor

import einops

from transformers.activations import ACT2FN

from transformer_lens.model_bridge import TransformerBridge

#make sure HF_HUB_CACHE is set to 1 if necessary, before loading datasets
if "SLURM_JOBID" in environ:
    environ["HF_HUB_OFFLINE"]='1'
import datasets

VALUES_TO_SUMMARISE = ['hook_post', 'hook_pre_linear', 'hook_pre', 'swish']
CASES = ['gate+_in+',
        'gate+_in-',
        'gate-_in+',
        'gate-_in-']
_relevant_signs = {
    case : {
        'hook_pre_linear': +1 if case[-1]=='+' else -1,
        'hook_pre': +1 if case.startswith('gate+') else -1,
    }
    for case in CASES
}
RELEVANT_SIGNS = {
    case : {
        **_relevant_signs[case],
        'swish': -1,
        'hook_post' : _relevant_signs[case]['hook_pre_linear']*_relevant_signs[case]['hook_pre'],
    }
    for case in CASES
}

def get_act_type_keys(key):
    if key[0].startswith('gate+') and key[1]=='swish':
        return []
    extra_keys = [f'{key[0]}_{key[1]}']
    if key[0].startswith('gate+') and key[1]=='hook_pre':
        extra_keys.append(f'{key[0]}_swish')
    keys = extra_keys+VALUES_TO_SUMMARISE
    return keys

def detect_cases(gate_values, in_values, keys=None, to_device='cpu'):
    """Given two tensors,
    return a dictionary with up to four 0-1 tensors
    indicating the four possible sign combinations.
    Ignores exact zeros (which probably come from padding tokens).

    Args:
        gate_values (Tensor or any type that supports >, ~ and * operations): "gate" values
        in_values (same): "in" values
        keys (list[str]|None): the cases we are interested in. Defaults to None (all four cases).

    Returns:
        dict[str, Tensor]:
            keys are the ones in CASES,
            values are 0-1 tensors of the same shape as gate_values and in_values.
    """
    # gate_positive = gate_values>0
    # in_positive = in_values>0
    if keys is None:
        keys=CASES
    bins={}
    if 'gate+_in+' in keys:
        bins['gate+_in+'] = ((gate_values>0)*(in_values>0)).to(to_device)
    if 'gate+_in-' in keys:
        bins['gate+_in-'] = ((gate_values>0)*(in_values<0)).to(to_device)
    if 'gate-_in+' in keys:
        bins['gate-_in+'] = ((gate_values<0)*(in_values>0)).to(to_device)
    if 'gate-_in-' in keys:
        bins['gate-_in-'] = ((gate_values<0)*(in_values<0)).to(to_device)
    return bins

def compute_sign_to_adapt(model:TransformerBridge)->torch.Tensor:
    W_in = model.W_in.detach().cuda()
    W_gate = model.W_gate.detach().cuda()
    sign_to_adapt = torch.sign(
        einops.einsum(
            W_in, W_gate,
            "l d n, l d n -> l n" if W_in.shape[1]==model.cfg.d_model else "l n d, l n d -> l n"
        )
    )
    del W_in, W_gate
    return sign_to_adapt

def refactor_glu_old(summary_dict, sign_to_adapt):
    """
    ONLY WORKS WITH SUMMARY FILES GENERATED BY AN OLD VERSION (BEFORE WE INTRODUCED PREPROCESSING)

    Adapt the summary_dict generated by b_activations.py to the refactored model.
    For the neurons that have changed under the weight preprocessing,
    the following changes are made:
    - max_activations and min_activations are exchanged, and their "values" entries multiplied by -1
    - summary_mean is multiplied by -1.

    Args:
        summary_dict (dict):
            The summary_dict generated by b_activations.py.
            Its entries are given by SUMMARY_KEYS and HEAP_KEYS in b_activations.py
            The values of the HEAP_KEYS are themselves dicts with keys "values", "indices".
        sign_to_adapt (tensor):
            tensor of +1 and -1, shape (layer, neuron). The -1 entries are the neurons to refactor.

    Returns:
        dict: the new version of summary_dict, compatible with the model.
        
    """
    #summary_mean is easy
    summary_dict["summary_mean"]*=sign_to_adapt
    #exchange max and min activations
    sign_to_adapt = sign_to_adapt.unsqueeze(0)
    max_activations_values = torch.where(
        sign_to_adapt==1,
        summary_dict["max_activations"]["values"],
        -summary_dict["min_activations"]["values"],
    )
    min_activations_values = torch.where(
        sign_to_adapt==1,
        summary_dict["min_activations"]["values"],
        -summary_dict["max_activations"]["values"],
    )
    summary_dict["max_activations"]["values"] = max_activations_values
    summary_dict["min_activations"]["values"] = min_activations_values
    max_activations_indices = torch.where(
        sign_to_adapt==1,
        summary_dict["max_activations"]["indices"],
        summary_dict["min_activations"]["indices"],
    )
    min_activations_indices = torch.where(
        sign_to_adapt==1,
        summary_dict["min_activations"]["indices"],
        summary_dict["max_activations"]["indices"],
    )
    summary_dict["max_activations"]["indices"] = max_activations_indices
    summary_dict["min_activations"]["indices"] = min_activations_indices
    return summary_dict

def _refactor_case(case_str):
    if case_str[-1]=='+':
        return case_str[:-1]+'-'
    return case_str[:-1]+'+'

def refactor_glu(summary_dict, sign_to_adapt):
    """
    Adapt the summary_dict generated by b_activations.py to the refactored model.
    For the neurons that have changed under the weight preprocessing,
    the following changes are made:
    - the in+ and in- cases are exchanged
    - and the tensor entries, or the 'values' entries of dicts, are multiplied by -1.

    Args:
        summary_dict (dict):
            The summary_dict generated by b_activations.py.
            Its keys are of the type (case, 'freq') or (case, key, reduction), where:
                case is of the type 'gate+_in-' (one of the four activation quadrants);
                key is an ActivationCache key;
                reduction is 'max' or 'sum'.
        sign_to_adapt (tensor):
            tensor of +1 and -1, shape (layer, neuron). The -1 entries are the neurons to refactor.

    Returns:
        dict: the new version of summary_dict, compatible with the refactored model.
    """
    new_dict = {}
    for key in summary_dict:
        if key[-1]=='freq':
            new_dict[key] = torch.where(
                sign_to_adapt==1,
                summary_dict[key],
                -summary_dict[(_refactor_case(key[0]), 'freq')]
            )
        elif key[-1]=='sum':
            layer=None
            if '.' in key[1]:
                layer = int(key[1].split('.')[1])
            new_dict[key] = torch.where(
                sign_to_adapt[layer,:]==1,
                summary_dict[key],
                -summary_dict[(_refactor_case(key[0]), key[1], key[2])]
            )
        else:
            assert key[-1]=='max', f"last part of key must be 'freq', 'sum', or 'max', but key is {key}"
            #print(key)
            layer=None
            if '.' in key[1]:
                layer = int(key[1].split('.')[1])
            new_dict[key] = {
                "values": torch.where(
                    (sign_to_adapt[layer,:]==1) if layer is not None else (sign_to_adapt==1),
                    summary_dict[key]["values"],
                    -(summary_dict[(_refactor_case(key[0]), key[1], key[2])]["values"])
                ),
                "indices": torch.where(
                    (sign_to_adapt[layer,:]==1) if layer is not None else (sign_to_adapt==1),
                    summary_dict[key]["indices"],
                    summary_dict[(_refactor_case(key[0]), key[1], key[2])]["indices"]
                )
            }
    return new_dict

def refactor_glu_model(
        model:TransformerBridge, sign_to_adapt:torch.Tensor
    )->TransformerBridge:
    dn_in = model.blocks[0].mlp.W_in.shape[0]==model.cfg.d_model
    dn_out = model.blocks[0].mlp.out.weight.shape[0]==model.cfg.d_model
    for layer in range(model.cfg.n_layers):
        model.blocks[layer].mlp.W_in *= einops.rearrange(
            sign_to_adapt[layer],
            "n -> 1 n" if dn_in else "n -> n 1"
        )
        model.blocks[layer].mlp.out.weight *= einops.rearrange(
            sign_to_adapt[layer],
            "n -> 1 n" if dn_out else "n -> n 1"
        )
        if layer==0:
            assert torch.all(
                einops.einsum(
                    model.blocks[0].mlp.W_in, model.blocks[0].mlp.W_out,
                    f"{'d n' if dn_in else 'n d'}, {'d n' if dn_out else 'n d'} -> n"
                ) >= 0
            )

def adapt_activations(dict_all):
    #TODO adapt to new format
    """adapt activations incl. order of examples to cases in which refactoring switched the sign.

    Args:
        dict_all (dict): raw activations for a given neuron (without refactoring)

    Returns:
        dict: same but adapted
    """
    topk = dict_all['acts'].shape[0]//2
    new_dict = {
        key: torch.cat((-value[topk:], -value[:topk]))
        for key,value in dict_all.items()
    }
    return new_dict

def add_properties(dataset:datasets.Dataset):
    setattr(dataset, "n_tokens", sum(len(row) for row in dataset['input_ids']))
    setattr(dataset, "max_seq_len", max(len(row) for row in dataset['input_ids']))
    return

def add_actfn(model:TransformerBridge):
    setattr(model, 'actfn', ACT2FN[model.cfg.act_fn])
    return

def _move_to(dict_of_tensors, device):
    for key,value in dict_of_tensors.items():
        if is_tensor(value):
            dict_of_tensors[key] = value.to(device)
        elif isinstance(value, dict):
            dict_of_tensors[key] = _move_to(value, device)
    return dict_of_tensors

def topk_indices(maxact, k=16, largest=True, use_cuda=True):
    """Wrapper around torch.topk. Not actually used in the current version."""
    if use_cuda and torch.cuda.is_available():
        maxact = maxact.cuda()
    _values, indices = torch.topk(maxact, k=k, dim=0, largest=largest)
    #sample layer neuron -> k layer neuron, entries are indices along sample dimension
    return indices

def load_data(args):
    dataset_path = join(
        environ["WORK"] if "WORK" in environ else ".",
        args.datasets_dir,
        args.dataset,
    )
    if exists(dataset_path):
        return datasets.load_from_disk(dataset_path)
    if args.dataset=='dolma-small':
        if "WORK" in environ:
            environ['HF_HUB_OFFLINE']='1'
            cache_dir = join(environ["WORK"], '.cache', 'huggingface', 'hub')
        else:
            cache_dir = None
        print(cache_dir)
        return datasets.load_dataset('sjgerstner/dolma-small', cache_dir=cache_dir, split='train')
    return datasets.load_dataset(args.dataset)['train']

def get_run_code(args):
    if args.save_to:
        return args.save_to
    if args.test:
        return "test"
    model_code = args.model.split('/')[-1].strip("-hf")
    if args.dataset in ('dolma_small', 'dolma-small'):
        return model_code
    return f"{model_code}_{args.dataset}"

def make_save_path(results_dir, run_code):
    save_path = join(
        environ["WORK"] if "WORK" in environ else ".",
        results_dir,
        run_code
    )
    makedirs(save_path, exist_ok=True)
    return save_path

def get_page_file_path():
    site_dir = join(environ["WORK"], "gluscope.github.io") if "WORK" in environ else "docs"
    page_file = join(site_dir, "pages.json")
    return page_file
